name: odssm-post-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9 # because of searvey
  - pygeos
  - geos
  - gdal
  - proj
  - pyproj
  - cartopy
  - udunits2
  - shapely>=1.8.0
  - arrow
  - attrs
  - backcall
  - beautifulsoup4
  - bokeh
  - branca
  - brotlipy
  - bs4
  - certifi
  - cffi
  - cftime
  - cfunits
  - cfgrib
  - chardet
  - click
  - click-plugins
  - cligj
  - cryptography
  - cycler
  - decorator
  - f90nml
  - fiona
  - folium
  - gdal
  - geopandas
  - geos
  - geotiff
  - glib
  - icu
  - idna
  - ipython
  - ipython_genutils
  - jedi
  - jinja2
  - kiwisolver
  - krb5
  - lxml
  - markupsafe
  - matplotlib
  - munch
  - netcdf4
  - hdf5
  - numpy
  - olefile
  - packaging
  - pandas
  - parso
  - pexpect
  - pickleshare
  - pillow
  - prompt-toolkit
  - ptyprocess
  - pycparser
  - pygeos
  - pygments
  - pyopenssl
  - pyparsing
  - pyproj
  - pysocks
  - python-wget
  - pytz
  - pyyaml
  - readline
  - requests
  - retrying
  - rtree
  - setuptools
  - shapely
  - six
  - searvey
  - soupsieve
  - tbb
  - tiledb
  - tk
  - tornado
  - traitlets
  - typing_extensions
  - wcwidth
  - wheel
  - zstd
  - pip:
    - pyschism
